// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/AlertsPage.tsx": () => import("../components/mockups/AlertsPage.tsx"),
  "./components/mockups/DashboardOverview.tsx": () => import("../components/mockups/DashboardOverview.tsx"),
  "./components/mockups/HistoricalData.tsx": () => import("../components/mockups/HistoricalData.tsx"),
  "./components/mockups/SensorsPage.tsx": () => import("../components/mockups/SensorsPage.tsx")
};
